### ISSUE TITLE
Set up CI + branch protection rules

### ISSUE THREAD

**Issue by gordonbchen** [applepi-2067/2024_Robot#3]

**Comment by jcorcoran** [comment]
I think this is addressed now

* [CI setup](https://github.com/applepi-2067/2024_Robot/actions)
* and I think branch protection rules match 2023 repo now as well:

  
  ![image](https://github.com/applepi-2067/2024_Robot/assets/1295877/69bc7d43-9745-4773-8794-8024c8f7b75d)
